# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        self.chineseTextEdit = QtWidgets.QTextEdit(Dialog)
        self.chineseTextEdit.setGeometry(QtCore.QRect(70, 60, 640, 160))
        self.chineseTextEdit.setObjectName("chineseTextEdit")
        self.koreanTextEdit = QtWidgets.QTextEdit(Dialog)
        self.koreanTextEdit.setGeometry(QtCore.QRect(70, 320, 640, 160))
        self.koreanTextEdit.setObjectName("koreanTextEdit")
        self.Chinese2KoreanPushButton = QtWidgets.QPushButton(Dialog)
        self.Chinese2KoreanPushButton.setGeometry(QtCore.QRect(70, 250, 90, 40))
        self.Chinese2KoreanPushButton.setObjectName("Chinese2KoreanPushButton")
        self.Korean2ChinesePushButton = QtWidgets.QPushButton(Dialog)
        self.Korean2ChinesePushButton.setGeometry(QtCore.QRect(70, 500, 90, 40))
        self.Korean2ChinesePushButton.setObjectName("Korean2ChinesePushButton")
        self.chineseDocumentPushButton = QtWidgets.QPushButton(Dialog)
        self.chineseDocumentPushButton.setGeometry(QtCore.QRect(180, 250, 90, 40))
        self.chineseDocumentPushButton.setObjectName("chineseDocumentPushButton")
        self.koreanDocumentPushButton = QtWidgets.QPushButton(Dialog)
        self.koreanDocumentPushButton.setGeometry(QtCore.QRect(180, 500, 90, 40))
        self.koreanDocumentPushButton.setObjectName("koreanDocumentPushButton")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(600, 510, 181, 71))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.glossaryComboBox = QtWidgets.QComboBox(Dialog)
        self.glossaryComboBox.setGeometry(QtCore.QRect(469, 540, 110, 40))
        self.glossaryComboBox.setObjectName("glossaryComboBox")
        self.glossaryComboBox.addItem("")

        self.retranslateUi(Dialog)
        self.Korean2ChinesePushButton.clicked.connect(self.koreanTextEdit.clear) # type: ignore
        self.Chinese2KoreanPushButton.clicked.connect(self.chineseTextEdit.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "LongtuKoreaTranslator"))
        self.Chinese2KoreanPushButton.setText(_translate("Dialog", "中 -> 한"))
        self.Korean2ChinesePushButton.setText(_translate("Dialog", "한 -> 中"))
        self.chineseDocumentPushButton.setText(_translate("Dialog", "文档"))
        self.koreanDocumentPushButton.setText(_translate("Dialog", "문서"))
        self.glossaryComboBox.setItemText(0, _translate("Dialog", "术语表/용어집"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
