# -*- coding: utf-8 -*-
import os

# Form implementation generated from reading ui file 'front_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from translate import translate_text_with_glossary
from settings import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        self.ChineseEdit = QtWidgets.QTextEdit(Dialog)
        self.ChineseEdit.setGeometry(QtCore.QRect(70, 60, 640, 160))
        self.ChineseEdit.setObjectName("ChineseEdit")
        self.KoreanEdit = QtWidgets.QTextEdit(Dialog)
        self.KoreanEdit.setGeometry(QtCore.QRect(70, 320, 640, 160))
        self.KoreanEdit.setObjectName("KoreanEdit")
        self.Chinese2Korean = QtWidgets.QPushButton(Dialog)
        self.Chinese2Korean.setGeometry(QtCore.QRect(70, 250, 90, 40))
        self.Chinese2Korean.setObjectName("Chinese2Korean")
        self.Korean2Chinese = QtWidgets.QPushButton(Dialog)
        self.Korean2Chinese.setGeometry(QtCore.QRect(70, 500, 90, 40))
        self.Korean2Chinese.setObjectName("Korean2Chinese")

        self.retranslateUi(Dialog)
        self.Chinese2Korean.clicked.connect(self.Chinese2Korean_clicked)  # type: ignore
        self.Korean2Chinese.clicked.connect(self.Korean2Chinese_clicked)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def Chinese2Korean_clicked(self):
        self.KoreanEdit.clear()
        for line in self.ChineseEdit.toPlainText().split('\n'):
            # 过滤空白项
            if line == "":
                continue
            response = translate_text_with_glossary(line, PROJECT_ID, "zh-CN", "ko", "glossary_all")
            self.KoreanEdit.append(response.glossary_translations[0].translated_text)

    def Korean2Chinese_clicked(self):
        self.ChineseEdit.clear()
        for line in self.KoreanEdit.toPlainText().split('\n'):
            # 过滤空白项
            if line == "":
                continue
            response = translate_text_with_glossary(line, PROJECT_ID, "ko", "zh-CN", "glossary_all")
            self.ChineseEdit.append(response.glossary_translations[0].translated_text)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "LongtuKoreaTranslator"))
        self.Chinese2Korean.setText(_translate("Dialog", "中 -> 한"))
        self.Korean2Chinese.setText(_translate("Dialog", "한 -> 中"))


if __name__ == "__main__":
    # 设置环境变量
    os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = os.path.abspath(PRIVATE_KEY_NAME)

    # GUI程序
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
